### ISSUE TITLE
安装了该脚本，NAI界面也出现了相应的按钮，但是无法实现脚本连续生图的功能

### ISSUE THREAD

**Issue by AdmiralKeyes** [crosstyan/generate-forever#1]
如题

**Comment by crosstyan** [comment]
Removing auto save resolve this issue. (I never encountered this problem since I always disable this toggle)
If you really needs auto save, NovelAI has already provide it.

<img width="479" alt="image" src="https://github.com/crosstyan/generate-forever/assets/49297668/b407e0ee-6443-40eb-9fa8-af6aeb8bfb1f">
